---
- name: Install Prometheus
  become: yes
  become_user: root
  block:
    - name: Import Grafana GPG key (Ubuntu)
      apt_key:
        url: https://packages.grafana.com/gpg.key
      when: ansible_distribution == "Ubuntu"

    - name: Add prometheus repository (Ubuntu)
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
      when: ansible_distribution == "Ubuntu"

    - name: Add prometheus repository (CentOS)
      yum_repository:
        name: prometheus
        baseurl: https://packagecloud.io/prometheus-rpm/release/el/{{ansible_distribution_major_version }}/$basearch
        description: Prometheus repository
        gpgcheck: no
      when: ansible_distribution == "CentOS"

    - name: Install Prometheus on Ubuntu
      package:
        name: prometheus
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Prometheus on CentOS
      package:
        name: prometheus
        state: present
      when: ansible_distribution == "CentOS"
